# disable deployment
deploy: off
version: '{build}'
clone_depth: 1
environment:
  matrix:
    - VIM_URL: http://files.kaoriya.net/vim/vim74-kaoriya-win64.zip
    #- VIM_URL: http://files.kaoriya.net/vim/2011/vim73-kaoriya-win64-20110306.zip
install:
  - 'cd %APPVEYOR_BUILD_FOLDER%'
  - 'appveyor DownloadFile %VIM_URL% -FileName %TEMP%\vim.zip'
  - '7z x -o%TEMP% %TEMP%\vim.zip > nul'
  - ps: $Env:THEMIS_VIM = (Get-ChildItem $Env:TEMP | Select-Object -First 1).FullName + '\vim.exe'

  - 'git clone --depth 1 https://github.com/vim-jp/vital.vim %TEMP%\vital'
  - 'git clone --depth 1 --branch ver.9.2 https://github.com/Shougo/vimproc.vim %TEMP%\vimproc'
  - 'appveyor DownloadFile https://github.com/Shougo/vimproc.vim/releases/download/ver.9.2/vimproc_win64.dll -FileName %TEMP%\vimproc\lib\vimproc_win64.dll'

  - 'git clone --depth 1 --branch v1.5.1 https://github.com/thinca/vim-themis %TEMP%\vim-themis'
  - 'reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:32'
  - 'reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:64'
build: off
test_script:
  - '%THEMIS_VIM% --version'
  - '%TEMP%\vim-themis\bin\themis.bat -v'
  - '%TEMP%\vim-themis\bin\themis.bat --runtimepath %TEMP%\vimproc --runtimepath %TEMP%\vital --reporter dot'
